In [45]:
## Homework 1

import numpy as np


In [46]:
# Problem 1
# Newton-Raphson method: x_(n+1) = x_n - f(x_n)/f'(x_n)

tol = 1e-6
x_initial = -1.6
x_n = x_initial
iteration_range = 10000
x_val_Newton = [x_initial]

for num_interation in range(iteration_range):
    f = x_n * np.sin(3 * x_n) - np.exp(x_n)
    f_derivative = np.sin(3*x_n) + 3 * x_n * np.cos(3*x_n) - np.exp(x_n)
    if f_derivative != 0: # denominator should not be 0
        x_n = x_n - (f / f_derivative)
        x_val_Newton.append(x_n)
        if abs(f) < tol:
            converge_interations = num_interation + 1
            break
    

x_val_Newton_vec = np.array(x_val_Newton)
A1 = x_val_Newton_vec



a = -0.7; b = -0.4 # end points
midpoints = []
for num_interation_1 in range(iteration_range):
    f = x_n * np.sin(3 * x_n) - np.exp(x_n)
    f_a = a * np.sin(3 * a) - np.exp(a)
    f_b = b * np.sin(3 * b) - np.exp(b)
    if f_a * f_b < 0: # In bisection, over interval [a,b] f(a) and f(b) have opposite signs. 
                      # When the two are multiplied, it should be a negative. 
        midpoint = (a + b) / 2
        midpoints.append(midpoint)
        f_mid = midpoint * np.sin(3 * midpoint) - np.exp(midpoint)
        if abs(f_mid) < tol or (b - a) / 2 < tol: #(if range between end points is smaller than tolerance -> break)
            converge_interations_1 = num_interation_1 + 1
            break

    # get new end points
    if f_a * f_mid < 0: 
        b = midpoint 
    else:
        a = midpoint


A2 = midpoints
A3 = converge_interations, converge_interations_1
A3 = np.array(A3)



In [47]:
print(A1)
print(A2)
print(A3)

[-1.6         3.19799514  2.46440244  1.2035359   0.65020146 -0.11692334
 -0.66052349 -0.52192654 -0.56655274 -0.57074658 -0.57078962 -0.57078962]
[-0.55, -0.625, -0.5875, -0.5687500000000001, -0.578125, -0.5734375, -0.5710937500000001, -0.5699218750000001, -0.5705078125, -0.57080078125, -0.570654296875, -0.5707275390625, -0.57076416015625, -0.570782470703125, -0.5707916259765625, -0.5707870483398438, -0.5707893371582031]
[11 17]


In [48]:
# Problem 2
A = np.array([[1, 2], [-1, 1]])
B = np.array([[2, 0], [0, 2]])
C = np.array([[2, 0, -3], [0, 0, -1]])
D = np.array([[1, 2], [2, 3], [-1, 0]])
x = np.array([1, 0])
y = np.array([0, 1])
z = np.array([1, 2, -1])

# a)
A4 = A + B
print(A4)

# b)
A5 = 3 * x - 4 * y
print(A5)

# c)
A6 = np.dot(A, x)
print(A6)

# d) 
x_y = x - y
A7 = np.dot(B, x_y)
print(A7)

# e)
A8 = np.dot(D, x)
print(A8)

# f)
D_y = np.dot(D, y)
A9 = D_y + z
print(A9)

# g)
A10 = np.dot(A, B)
print(A10)

# h)
A11 = np.dot(B, C)
print(A11)

# i) 
A12 = np.dot(C, D)
print(A12)



[[ 3  2]
 [-1  3]]
[ 3 -4]
[ 1 -1]
[ 2 -2]
[ 1  2 -1]
[ 3  5 -1]
[[ 2  4]
 [-2  2]]
[[ 4  0 -6]
 [ 0  0 -2]]
[[5 4]
 [1 0]]
